services:
  client:
    container_name: chatdrex-ui
    image: gitlab.cosy.bio:5050/simonsuewer/chatdrex-ui/ui:staging
    restart: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - '8131:80'

  api:
    image: gitlab.cosy.bio:5050/simonsuewer/chatdrex-api/chatdrex-api:staging
    container_name: chatdrex-api
    ports:
      - 8132:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: on-failure
